language: java

git:
  depth: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      compiler: clang-8
      jdk: openjdk8
      env:
        - ARCH_DIST=linux64
        - CC=clang-8
        - CXX=clang++-8
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-xenial-8 # https://docs.travis-ci.com/user/installing-dependencies/#adding-apt-sources
          packages:
            - ninja-build
            - cmake
            - clang-8
            - lbzip2
            - build-essential
            - libgtk2.0-dev

    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: ARCH_DIST=macosx64
      addons:
        homebrew:
          packages:
            - ninja
            - ant
            - lbzip2
            - gnu-tar
            - pyenv
			- cmake
          taps: AdoptOpenJDK/openjdk
          casks: adoptopenjdk8-openj9

    - os: linux
      services: docker
      env:
        - ARCH_DIST=linux32
        - CC=clang-8
        - CXX=clang++-8
      install:
          - docker build --rm --tag travis-build .
          - |
            docker run --volume "$PWD:$TRAVIS_BUILD_DIR" \
             --workdir "$TRAVIS_BUILD_DIR" \
             --env ARCH_DIST --env CC --env CXX --env TRAVIS_OS_NAME \
             --name travis-build --detach --tty --interactive --rm travis-build

# see https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"; fi 
  - unset _JAVA_OPTIONS

before_script:
  - export JCEF_DIR="$PWD/src"
  - source ./prepare-build.sh

script:
  - |
    if [ $ARCH_DIST == 'linux32' ]; then
      docker exec -e JCEF_DIR travis-build ./build.sh && \
      docker container stop travis-build || travis_terminate $?
    else
      ./build.sh || travis_terminate $?
    fi

before_deploy:
  - cd ./packaging && ../prepare-deploy.sh $JCEF_DIR/binary_distrib

after_deploy:
  - cd ../

# for encryption, see https://docs.travis-ci.com/user/encryption-keys/
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_RELEASE_TOKEN_PRIVATE
    file_glob: true
    file: build/distributions/*
    on:
      tags: true
      repo: smac89/java-cef-build
  - provider: pages
    skip_cleanup: true
    keep_history: true
    committer_from_gh: true
    github_token: $GITHUB_TOKEN_PRIVATE
    local_dir: packaging/build/install/java-cef-build-docs
    on:
      tags: true
      repo: smac89/java-cef-build
      condition: $ARCH_DIST == 'linux64'

env:
  global:
    - secure: "WRaDo3ndQOR5ATmjE9+EDlYnIsanPB6ItvaRbahMt2WlzLYKIBMY+ASmNVoAABykOpBkoNeKS4cIEnNueCxHU0LNfZyMvTDkuRm0s0wovyKXaEwAgRgnP6xCmnZ6V8VjTWNSl43tTcF++5S3Yx+lJdLzKWx2v/hbN1/Vb7LK6guLGLvyKlg2n2N76v/3rK2C9w5haMIrDAqCPHNnxpVYPxR2Rzqs0OmkH3GFu7YUVdfQ48RWdivKIu8NPUzDZMI3IvwFm/Ba6Sdk8y0i/z21IlBMbPQwN2vQzM9kelvO3+ZLx46DaO2s1oGXvz7T2YDzsZxQz97PMms7DyMo4t6ejF9C6feQutCOuybOAWEPkxSVXQe9XvP4jQbn1JVfjK2evqFUU3OWIxiwJJYbT/QZ7Pdmp/4GqknPzCtHihE2pawzQn/B3B9mksz6/c28UoeWy2XFQ3RnipLDTBvaJo7NQm6RngbrWhFSQRHFVQqqzw3jR4LvJFX8L6+R5bueJiXExE408hu2UUXmxskQJAWmDaFsiB2QZLaILFXx9l/bUhi5pQGL4t2jp+fVSE8u3fwev16cH0kMpnr0JhN4/hA9Cviq+V8yfVs0bbjke6dCAIMxEUOl8OolJ/N2am4sekLSwITy4QUaaS4BEqkuqLne+rAEDtKER5rR6H3BhrQzDk4="
