language: java

git:
  depth: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      compiler: clang-8
      jdk: openjdk8
      env:
        - ARCH_DIST=linux64
        - CC=clang-8
        - CXX=clang++-8
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-xenial-8 # https://docs.travis-ci.com/user/installing-dependencies/#adding-apt-sources
          packages:
            - ninja-build
            - cmake
            - clang-8
            - lbzip2
            - build-essential
            - libgtk2.0-dev

    - os: osx
      osx_image: xcode11
      compiler: clang
      env: ARCH_DIST=macosx64
      addons:
        homebrew:
          update: true
          packages:
            - ninja
            - ant
            - lbzip2
            - gnu-tar
            - pyenv
            - cmake
          taps: AdoptOpenJDK/openjdk
          casks: adoptopenjdk8-openj9

    - os: linux
      services: docker
      env:
        - ARCH_DIST=linux32
        - CC=clang-8
        - CXX=clang++-8
      install:
          - docker build --rm --tag travis-build .
          - |
            docker run --volume "$PWD:$TRAVIS_BUILD_DIR" \
             --workdir "$TRAVIS_BUILD_DIR" \
             --env ARCH_DIST --env CC --env CXX --env TRAVIS_OS_NAME \
             --name travis-build --detach --tty --interactive --rm travis-build

    - os: linux
      if: tag IS present
      jdk: openjdk8
      env:
        - ARCH_DIST=""
      script:
        - cd $JCEF_DIR/tools
        - ./make_docs.sh
      before_deploy:
        - cd $TRAVIS_BUILD_DIR/packaging
        - ARCH_DIST="/" ./gradlew --no-daemon -DBIN_ARTIFACT="$JCEF_DIR/out/" --quiet installDocsDist
      deploy:
        provider: pages
        cleanup: false
        keep_history: true
        token: $GITHUB_RELEASE_TOKEN_PRIVATE
        local_dir: packaging/build/install/java-cef-build-docs

before_install:
  - |
    if [ $TRAVIS_OS_NAME = 'osx' ]; then
      export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
    fi
  - unset _JAVA_OPTIONS # see https://github.com/travis-ci/travis-ci/issues/8408

before_script:
  - export JCEF_DIR="$PWD/src"
  - source ./prepare-build.sh

script:
  - |
    if [ $ARCH_DIST == 'linux32' ]; then
      docker exec -e JCEF_DIR travis-build ./build.sh && \
      docker container stop travis-build || travis_terminate $?
    else
      ./build.sh || travis_terminate $?
    fi

before_deploy:
  - cd ./packaging && ../prepare-deploy.sh $JCEF_DIR/binary_distrib

after_deploy:
  - cd ../

# for encryption, see https://docs.travis-ci.com/user/encryption-keys/
deploy:
  - provider: releases
    cleanup: false
    token: $GITHUB_RELEASE_TOKEN_PRIVATE
    file_glob: true
    file: build/distributions/*
    on:
      tags: true
      repo: smac89/java-cef-build
