name: Publish the JCEF Javadoc Website

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout JCEF-BUILD
      uses: actions/checkout@v1
      with:
        path: jcef-build

    - name: Checkout JCEF
      run: |
        git clone https://github.com/chromiumembedded/java-cef jcef
        cd "$GITHUB_WORKSPACE/jcef"
        git apply --verbose ../patch/build-tools.patch
      shell: bash

    - name: Generate Docs
      if: success()
      run: |
        cd "$GITHUB_WORKSPACE/jcef/tools"
        ./make_docs.sh
      shell: bash

    - name: Build Pages
      if: success()
      run: |
        cd packaging
        ./gradlew --no-daemon -DBIN_ARTIFACT="$GITHUB_WORKSPACE/jcef/out/" -DARCH_DIST="" --info installDocsDist

    - name: Deploy Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.0.1
      with:
        target_branch: gh-pages
        build_dir: packaging/build/install/java-cef-build-docs
      env:
        GITHUB_PAT: ${{ secrets.TR_GITHUB_TOKEN }}  
